apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-dns-secret
stringData:
  api-token: ENC[AES256_GCM,data:PXg00fQ3WOVibhCbH9CWb8A/IL9tkgC1ImeXnr4mDOgB6GIDqbU64A==,iv:zsVNzgQAtCuhCr+6l9uJtiCMT3gmQ7uQrzIVHbDc8cY=,tag:j8Lk0/0ixKhaqblLZ/6Zkw==,type:str]
sops:
  age:
    - recipient: age182kynq27uxu9tdjrk8neh0hztkra3xrxhjumwxsq9np9ms0ah5hsd0gjkz
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwMEhGQ09Cejlhd0JWNzQw
        S0pxZXFNM2dPQzVYeDJGeWZBd2QvaE03QXg0CkJnZHFuaTJrMUJ1TU9EZmZCYms2
        Mi84Vml5TStRNlQ4ay84NUxGSTZsOTAKLS0tIGlhcmlqalBIU0czb2cwQ242bjhy
        dmIwSnNBOXJkRytBN0Y4ZnpPYmt2NWMKy2Un0u7ApfIOfLNxoKN71nwZP+MR00cl
        wAxqemKO8llbS69r/IXIrGJBHamwgOD+vdAMCs6MKuuAldB2mv0Qjw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-01-18T12:04:46Z"
  mac: ENC[AES256_GCM,data:6TmHQKco79nd20l4tQv5nCkLIxmqW6aSo7WEfwAz52n8alcLIGaxrU4BEmJnNey4G04q1RGep7FOQWWUaqxZAgxNoWN3VCqJB15Q2KqNy3A4zTl5K7fGIPhPy099ytI6/ifuiHKaY7AZ6KVAOTgJZsPqvyGYb0cKIPl8m+rsi/8=,iv:DC3ICodHcMUqKqzTKvcZr7rBWVjZZb7kL4YFg+Kd5oQ=,tag:myXPW/lYLH/PlO41EIEE4w==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
