apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-dns-secret
stringData:
  api-token: ENC[AES256_GCM,data:QFbojb9sUxPRMRk3mJ+67L7Ro9IUae6TymS/UjHv0a9EnD/TLakXTQ==,iv:YpoJQjwmTINXxETfrYBhfI7wWBG46wmMWpCkqm0MHZU=,tag:KXRMpvkprQJfaDnlfpHShQ==,type:str]
sops:
  age:
    - recipient: age182kynq27uxu9tdjrk8neh0hztkra3xrxhjumwxsq9np9ms0ah5hsd0gjkz
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBRTIvc3UxNjVMbllxMk5x
        bWlERTNYQlNNWE85ZnZFek1ocFlCTldTK2pNClArNGxRQ0lDLzgwQzdRb1BDbzRr
        N3N1SldjdzBWTmRoN09Gd2NMei9BYlEKLS0tIEZWT3czdFN5b2FNOU5Ucmw2VTBH
        QnRFQ1VuL1ZpdS9kemFvVXN3ak5wRXMKwvDDc5qsxPVtdKGoPTLzNroRv7PcHu+6
        EWgjyrIaKhpAR/zGT1Vg6AUNqrillkiQy+cCtUY7e9g+ie2wAI4Ohg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-01-18T14:43:05Z"
  mac: ENC[AES256_GCM,data:JpfAw1jD/IUt8C1LeLSQj8PBQUZF769NDUEPYIqW8O++XcH5KWFLOs0VrN3xYDGPmO6oHyCzAy7GG/7j4EoipFpdaQKXRvAJtLrjmVp2aE85ZPPUMViMmcvmWyXGgEFQhgAbcLYueF6skBSS6dSlfiYESocQRbILP7WJKhWpZoQ=,iv:3f2rtBvtRE/TCD9ywlDJj+UTwUMUWefy5FR2fdvTBds=,tag:fjvEPIrvMvFIEItSxVKVUA==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
