apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-dns-secret
stringData:
  api-token: ENC[AES256_GCM,data:kuC97IwcFcT+5k2gskMA8TZzRrZ7guvmz1l9DByNGQd/Tpnpte7KIQ==,iv:qn8ZfeqviiOjC8/fYcnRB1MNDF5zlHiMIOLQZGGNC3c=,tag:qYV9kSozbL4BF1kmRARz9g==,type:str]
sops:
  age:
    - recipient: age182kynq27uxu9tdjrk8neh0hztkra3xrxhjumwxsq9np9ms0ah5hsd0gjkz
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAvcitXRkpDTGwyWGptTE1R
        Z2VOek9LdW9EQ1pIeUsyeUhxSDNEUERiaGcwCi9wdnRmQ2h4T0wrUG5JRkZPdkR2
        SXpTekNZYXlVMVhEVFN1c1RqelNud0UKLS0tIHdweExzRnhPeE5wM3cwUml0ZTlS
        WklLK3ZYQnBCRE9OYVh5VTJUOFdNcmsKE5DpObbfgwf845q3odwa7BLTk+cFGOCQ
        vedM0R3riKVzcQqq+zjtGsNs4NVKspzWCSE7gAzSmqU6rpogqTYXsg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-01-22T15:34:48Z"
  mac: ENC[AES256_GCM,data:av/LUudb2Y9+phWz0WplWyI77Gm8vzvq79o+GIXZ0yL3sJT434VV74xEMuyezGA0Nze5snY6YKwoXzG6yR92Z9n/nxB247AIoTV6FC2umx4pBt91l2kf6M0mQUGDigVcTPNCcdtQoxY0mklUVIW6fBUQFKyA1Xxv6y4vQlGqmp0=,iv:eHr3FxETrraFRWG8USfAjecLdxQdM+yIXJzz25t7Pfk=,tag:zXbBDihFZsfnQmLBk1s96w==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
