apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-dns-secret
stringData:
  api-token: ENC[AES256_GCM,data:kPR+ZIRB3pbIPUQNmo5/rG9O0lIzCTlRNr2egkevCl9HBCtBo3llWQ==,iv:4npalpAuxRQ8GWrVN0zSB0GFIkrXqyI+pWbymKBZqh0=,tag:BS6hi+8ncnUsiTdlmOZY5g==,type:str]
sops:
  age:
    - recipient: age182kynq27uxu9tdjrk8neh0hztkra3xrxhjumwxsq9np9ms0ah5hsd0gjkz
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBieUg1VnlEZWlPUkJ3ZWRG
        dUF3bm9ENlljQWEvVThVSU1ndkdwUHhwMG1JClVxODlla2UyTGxCRnVnMElHQ3JB
        NExoa2ptRG1lVHFEWkdmRy81Z1VJbHcKLS0tIEJlZEQ2aEoyY2Z0d2NiWjNKdDl3
        L01zTVBNWGlSb0VzNWFwV0poK1lTMXMK+wDtsrWefxNNH518Lsd6vgZJLCGhmizx
        jGl663vwwX0+aGBsXA8Q7u3GRSPEkVCXbJLZ2tM1aIcgDYsuvIJljw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-01-17T18:35:42Z"
  mac: ENC[AES256_GCM,data:X98UEAUC6hPqKhs4RjifubRSTm5L9ggixjllOCJ4gaZmd6bmn5oKmBYff/VeNZbJHizOuCKnjS/VsSqn/vNfeJ0Tl14JYs/n4N3bJz7bOy+oRKQ8ILtQqd2omVr1MjRjUNrinubk3dyyCUoRab89/fcYMHBIJIqly14qRjHejgo=,iv:x4uz/zJ1WBVrt6mn1aM/vV1HnMizJIfz3jjp0iolwu8=,tag:T3hkU0Ah02JgX4/7pruZQA==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
