apiVersion: v1
kind: Secret
metadata:
  name: cluster-secrets
stringData:
  SECRET_DOMAIN: ENC[AES256_GCM,data:skUB7o1k7DP33pGeSKNd,iv:BCcIat0YU2853LrD8yJaVa1IA+0pQ/xGFQdLu427itI=,tag:Ej7nApn0Vt+kuxP4hLeoNQ==,type:str]
sops:
  age:
    - recipient: age182kynq27uxu9tdjrk8neh0hztkra3xrxhjumwxsq9np9ms0ah5hsd0gjkz
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2T1dMVUNZQ3VMR3FCVXk5
        WE10b0V5aWVRU3AwZzdlYmpjSUtwVmF4WGowCjVzY2VZbkpDRTdKOTFpbHRRU0RW
        eGE2MnFhcU1EQmVOWjlQUW51QTVYS1UKLS0tIFdQWktIT2ZJZHo1aXZEQ0lmak5W
        VFJXNHNVaDV1cFR2VGJ0THRvRXBJZncKP9wOcaXA3wZ/43fhSBfQpjoU7cm1R307
        PueBHDdrdzysLp/HXxrXs2daFJlyRgd/p3ISvkkUPasofqtB/Gc+XQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-01-17T18:35:42Z"
  mac: ENC[AES256_GCM,data:2yxpaNxMfL232q5rddz3K3kZvbQY6MXNCYILK8qmlgcV/Y2XHGUxgkV7H6/byRA/pDWSqZBZg+YfKSgQ2QxcDruK+SDZKZVFS1WC1+LiUj1i5jJIgg5xwHvEx/cRqLqvg7UKUGKGcmKRhj5S8eMWpun1LXS5SbdelvvV2T2gKw8=,iv:EClB46SwOSG7PHYEmxfq+3GF75Dj8A8iDeefizGdVwU=,tag:RKb+tmUKRsb4bHQuvNC3UQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
