apiVersion: v1
kind: Secret
metadata:
  name: cluster-secrets
stringData:
  SECRET_DOMAIN: ENC[AES256_GCM,data:hsvaayxLzX3rJrbLXmAz,iv:79l5wcBP5WtIX3/xwyHFRT3B4Vab832QfZKKSBzp31c=,tag:6LR/9qtCD/3Tm36Mi5G7og==,type:str]
sops:
  age:
    - recipient: age182kynq27uxu9tdjrk8neh0hztkra3xrxhjumwxsq9np9ms0ah5hsd0gjkz
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmQnZKOE1HU2d3NzRTODZL
        ajUzNEs0WkNUV3E0N2dMSXozUHB6OUpFeXowClNFcUFwNDJPYTlaNE1pa1ZSVWtQ
        c3VoTWJmQTZ5aFhzbGExa1ZwNWFLMkEKLS0tIEgxRlBtTk5kK25jTGZ0Y1QxakhG
        aVUxTEVPQUM3WmJHeUFpdmprOVFob3MKuuRGNuYmy5LPF6DHF2abZK2eeG8dBqv5
        wezI0sClbH1OltSOqp2W6+GoGwsA2+utIiZfg0IJak3qwawKT8aWSg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-01-17T18:25:22Z"
  mac: ENC[AES256_GCM,data:RClxuF7yzoajJW82QYdzry2THzzejM5yp2KspgXDY7YUpREn/S+Kbpba/lXBraUtMYhuSxxJdcTr6LTDo9xkVd/2n+gLkeqGIlmg+5kaiPoMFlEVVoMS15oXDSv5Iv19QVeS9c1x/fiSrjGT+WXYKE4CrL6b/T4reYYMCP/Yu7Y=,iv:Ln09gUktcAFVQpcT+XdkIdtSae+H9LVfu2qt52H2Rms=,tag:dl5xMNRzyo/MPr0B86aB8g==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
