apiVersion: v1
kind: Secret
metadata:
  name: cluster-secrets
stringData:
  SECRET_DOMAIN: ENC[AES256_GCM,data:H9ytp+7Qp3uCGnFZ2Dbj,iv:HCaTjGkvwd1SkBjjooWmRR0acjQsq2bw34dQoCoS+3w=,tag:Yf1iFaEqY7raGDQr5N3ajw==,type:str]
sops:
  age:
    - recipient: age182kynq27uxu9tdjrk8neh0hztkra3xrxhjumwxsq9np9ms0ah5hsd0gjkz
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBnSDl3eFgzaU84aTlLeTZs
        RVZHUU51UjZnWTZoc2U5cWhzM0VPTWdrV1NvCmN3dFJBVTlJZnc2T2VkYWtSZDlJ
        WUM2UFBrNFRIbVRhOENYdmRYS28yYkkKLS0tIDMrcXl3WkZWSmpzRjNvVkR5WTZD
        WXRjRGhRdWdrbXArOTlGTVNoSFNCcHMK55lFr9j1gW/XgokOGEBDBDHPLO9PPbFQ
        ETL/PCRQXSE1ofUisL6pVME2Bs1SKHPSpo2UdQ/6bUbsqyCusqFQXQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-01-22T15:34:48Z"
  mac: ENC[AES256_GCM,data:BnZJNZVxD9rC19FjXUawoRQ8FIvuZiB4S99cQmIx9jV4RSR7kNYwavBOTpICOYJ1Emvl3sczfxSZc4Vx9MCd+6bgEP+sY1R5gfxn24hI01BHNfW0xRUR7HOU0U6eRk1yKhtR3V23N0MV96R1OcHOQ3PTv94DsfP0IWdfa7BWQtU=,iv:9Mjhxwzm+oGxckg0D5lGXNtsAYsEj1Gjd+Br6McqIgE=,tag:Kv47Z7+phrhh3JIURVw7MQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
