apiVersion: v1
kind: Secret
metadata:
  name: cluster-secrets
stringData:
  SECRET_DOMAIN: ENC[AES256_GCM,data:OqB7wtmbTtMapcOESpcR,iv:uEpraoSdX+SDRFolVzlJD5nP9V3wnw8RksrNTzhbmRo=,tag:wzNnL3evhi9Q/WCbY2Txsw==,type:str]
sops:
  age:
    - recipient: age182kynq27uxu9tdjrk8neh0hztkra3xrxhjumwxsq9np9ms0ah5hsd0gjkz
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA1dW9uTklTcDNGbGt0NHhI
        aTExdGRNSXkxa2kwWUlqTWl0bU5WS05xZDA0CjlBRGpDcDBxVThaUlR6MFVpNVhs
        ZUFCUnVvd0ExVUxKOWxhb1FxNHFTTTQKLS0tIHB3aWtuMzNPTU1Wd2lkakpNeDBa
        NWcrY1U4VmJLNlU5azFEQnU3ZVFvdmsKwoDX5CT5OCqINYOlVzsmMolFHdQ6wK0k
        IZgkRkrw79do0iIqd60iGz6i2LjGmGKX/M2ZkHPjvPLDN7SHbECTDA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-01-18T14:43:05Z"
  mac: ENC[AES256_GCM,data:lDFka/IKePlEDpGKqYqzzp9GGosYULn97Rof9UJkvmbv5OZiS151b3m5UM2vKE1M4TXFMQMbZihIxIGaIP67QePg5F0WaS/0Rzag/frMeou/V4GJ6YA3qVcGbZ/DQZGb1h/ioKODSU81JtU3IjKPm+gVDnp2jRqv3bek9VP0WHA=,iv:CsTwmisFBHt1wkb9ZdXAHMIasEg+IKT4ubQjwwQ4iBY=,tag:YNtbPlntobIX+oztA7MhQg==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
