apiVersion: v1
kind: Secret
metadata:
  name: github-webhook-token-secret
stringData:
  token: ENC[AES256_GCM,data:B/pLQIrbTC9/ltU0qCBr0mcw32qKq+tEdPz6OK2Psf0=,iv:IQnkifvZeErD1ojvYqJs+HfxsRrs0PLKnyP1P4eL6jU=,tag:gU5N+HLSBf5R+38ZfmPmhg==,type:str]
sops:
  age:
    - recipient: age182kynq27uxu9tdjrk8neh0hztkra3xrxhjumwxsq9np9ms0ah5hsd0gjkz
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBFbGM1YWdoNXlROXhBSTJW
        MVZ4SXczSEpOUzI4ekV1NXRMbUNVTzNLTmlBCkY4cE9icWdpOHdYRkhlZDQ2U2FO
        QXlYb0FNSlBCbnRJbHM2c1RJQTA2MFEKLS0tIFpTZWFlVjhuYWs1WnhWc1Z5NGg2
        NVZ2SXpOMUxFbkZ2bGhGN0xiUk9kMlUKjhvulXYVoOmHI9246ZnQeSQ60wgNPrA9
        xWSPMQXkZP0v20ln0QdD5QgZRh8/aeOwuxlmGer9aOHpUOSDiS01Fw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-01-17T18:35:42Z"
  mac: ENC[AES256_GCM,data:8QFCOnhKaYgV0lQokVeLQGupTCBSrhZa8RLwX3ALIDyfgdFz3+XojQGWqzGGzDuak9J2jrglzf5rSOC77pUbAPXAIDUuUsX2LNH5xbyBD33gbtCGzKdXOPY/u5SeKM40N1w4bFACV/YJEJ6qBqxQmqiiPt92Rv7ebNgKSM8UhjE=,iv:26PNbGrvM6UMRpF74dv1AsiX5wR12yURCe9O3II37p4=,tag:D5O8+a6S8So48kLpjykvqA==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
