apiVersion: v1
kind: Secret
metadata:
  name: github-webhook-token-secret
stringData:
  token: ENC[AES256_GCM,data:yrXxR6X2jp7zWq5nOBCJfUgN/hjPe0r1sX58R5SrDV8=,iv:hjZUgjWkVzSf1jVMYrTR88jhKcLWnpNQTRgki5XHUuw=,tag:nmJcQuXODwvrtCZjPYQD2w==,type:str]
sops:
  age:
    - recipient: age182kynq27uxu9tdjrk8neh0hztkra3xrxhjumwxsq9np9ms0ah5hsd0gjkz
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBFdjRaQi85QmdKZTBNWHVH
        S3dqc3hSM29SVW9BSFN3Z2hBS3hWS04vUUhVCk5STGpNRDVZUnZNL0xRUTFJM2Q4
        TkIxb3puaUNnaTlLVGlUUGtyV1R3T3MKLS0tIEhrTm5XeGc5SHp0MDZoYzZiZVVR
        VDhtOGZucmt1VjdzVVBSVXhJYjVTWFkKNVpvp8J0SMfaSUpC4b9W2IG/BdOzkTpx
        /6Dm/KmmEtws42h2HHpsRNnpC3D1NWJ/DC0oYJJDW9QMVVhlRKZ07A==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-01-18T14:43:05Z"
  mac: ENC[AES256_GCM,data:pRQB+x1BtF5+at/lQShvfDKE4iPNlJlNs6dSZ4Bpl3Pm8xCXGdA8qL1YoGNUnib5RtjMuxIndjx1p3IUV7FhcmmOzV36o0S8g7xq/hg3JxiNlYACZRsTMyxdRYMOl8KOYWrFYAwCoX4ysGmmlpy6FNUDDIdKm8X4L2CNMinBaSY=,iv:saqtOrnPhzZUP92XiJHDhJPUpw65eAOjkOMwLfeSUR0=,tag:if57nIlvNt0M+Mo7SMaamw==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
