apiVersion: v1
kind: Secret
metadata:
  name: github-webhook-token-secret
stringData:
  token: ENC[AES256_GCM,data:wuAdvdTCx02Ck+pjna1n6rYJ+QUTKRGairOgGjJJXYw=,iv:m8dTdLoVmyS0/PWcuZYpOa4EFKjIBj/g8r7l0j8tvyI=,tag:oDZcWdSmX3hXtd3QswH4Dg==,type:str]
sops:
  age:
    - recipient: age182kynq27uxu9tdjrk8neh0hztkra3xrxhjumwxsq9np9ms0ah5hsd0gjkz
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA1THlBdnZ0eVBQUmE3dDI5
        YVRxSm1jY3FHTi9iMitNWG1mSXM5RU4ySkVBCnhDc2NXWkk0bEo4NTlDS0RlOG5i
        NmZIYXROZXhNckxZL2JmTEFSWlV6aVkKLS0tIGc0TUhRVW4rZkxvaFFYRkoyOTVs
        ZzJUUkx0ZHdqVDNyMmNpVTdUdG55YVUKSuKNYHEo3l2tRhnL3lrcuQaf/d7BcxH0
        X2TyIL+YsTpvc023tK+Y01COukM5TMJBF37igGM2Dge3+ReadEnCIQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-01-18T12:04:46Z"
  mac: ENC[AES256_GCM,data:fOxb9zBFA/nLVZFZ5b5H8WIm3H4E03pMzQ4W1Mr7WTr2zHalu+mzmArjxcs2+Ac0onun9JxnQvnUpkcaDf7ad2TRdVg2ScM3XHMFBf/2xBBLGccSdSzvZdr4PEynFGwE2jR1HhDNOXPZs32L/afD3NUgXm6LFz0tzVd8qvzW1ZE=,iv:AogRY1mCcwf6jzZh+L6N1i+MGbzPNP5Eyo4rCQfMt3Y=,tag:79579J7SPTrhPaKh/W9buA==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
