apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - argocd-secrets.yaml
  - argocd-ingress.yaml

replacements:
- source:
    kind: Secret
    name: argocd-ingress-host
    fieldPath: data.hostname
  targets:
  - select:
      kind: Ingress
      name: argocd-server
    fieldPaths:
    - spec.rules.0.host
    options:
      delimiter: INGRESS_HOST_PLACEHOLDER
      index: 0
