apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - argocd-ingress.yaml
  - argocd-secrets.yaml
  - argocd-ingress-patch-job.yaml

configMapGenerator:
- name: argocd-host-config
  behavior: merge
  literals:
  - hostname=INGRESS_HOST_PLACEHOLDER
  options:
    annotations:
      argocd.argoproj.io/sync-wave: "2"

replacements:
- source:
    kind: ConfigMap
    name: argocd-host-config
    fieldPath: data.hostname
  targets:
  - select:
      kind: Ingress
      name: argocd-server
    fieldPaths:
    - spec.rules.0.host
