apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-tunnel-secret
stringData:
  TUNNEL_TOKEN: ENC[AES256_GCM,data:+be0DofQ/EkwyNaczrmldiIRrnMGujpQVOnLYLjm6bKa5zBI3q+uzAmc6vBHQx2vIjs06DhBDisSMGvVGH6QaTqadgBsiAO1UONvod0qOBhZwQTTvQ0mgKnVIibCU9+g/uS2LUsDWPBXzXAt33ITr+xo+Q6gCei4ZWTTQYmsAIDPHdfsISsC931ylLN6zqXJWlIX/IKVAItcR6TUJ8BfdnH0Jk0yRG/9pFvuVW/CSP7SHaIs,iv:zNCURckODJqhfQ0hEkfbTOrz1moFQ8fF/QZMQ3EqCcE=,tag:lgv5vGEjSB+vz/2gt5oa4A==,type:str]
sops:
  age:
    - recipient: age182kynq27uxu9tdjrk8neh0hztkra3xrxhjumwxsq9np9ms0ah5hsd0gjkz
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSByNEpMbWFMeGpYcVc3cTFx
        bFE1ZXA5UVU0d2xWV29GVFA5WUVyaGg3L0hrCldoTWdrZGdUYUhBTnFpZDhBSThI
        YmhXN2dkZDZoR1hicCtYTTF4NTVjUkkKLS0tIHl6Q0dPTFNEZ00ySW9MemJ4OWUy
        Rk93cExNdjNxQmhpUXlRV211SHl3T28K44BPd14hv7j4NlFWtGJi3OOg+B/tIaln
        0yklIefIsyMgHvOL4V3uHJyJCezwqx6nU4pMQLRIogjPMPlbpxLoyw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-01-18T12:04:46Z"
  mac: ENC[AES256_GCM,data:7WUrNzkj4GI3s2u+Em0CxSdLEIVDjZ2sUoJSqspAnVXZi83ZnDz8/mD6t9opSfQCOPcVl2z1cB2uMwGW+neitizpacVvmm0qVOyg+uY7uiaVkoVH8s0vw5NTUblFLPnnduEIIhyMvBFrhOgOBofYTwgIMg7VCDpMXuN+ATooX7w=,iv:pTZNhlxo1y+fW0hOcNu18jkeATzSDCxpFyqjC7Nt4Tg=,tag:Fp3dv0A+O0TsS1N1/alvog==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
