apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-tunnel-secret
stringData:
  TUNNEL_TOKEN: ENC[AES256_GCM,data:KpIEm32rWdJnV2WD9hltWxOZBpKD4yvxgO5MBWo2cb3bsCF+lS5pQLVvs3ZJL0Rc4WxRC1VeMvpNh4sV6o6X9YdOJ4feYMaPaj8P62GnaPwk5p2Wtrg9FPzJvvDl75lcKl9s0bgynbpTIJmMbyZn/yDtMzZ2GdZfBRL+XTlL6IIlCct68BJ1bSnx/rM1ya2voC2vapVW+6MlFjhHv6qgB37bAvp0rNZgSqzjkvwY/tK1OzXu,iv:eNgR2PITlCP8o7Hvl86CVzb8lhlSwLnfxP2Ghv2uTRU=,tag:TpDW6BUrGep8oZLcfeDvGA==,type:str]
sops:
  age:
    - recipient: age182kynq27uxu9tdjrk8neh0hztkra3xrxhjumwxsq9np9ms0ah5hsd0gjkz
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2TlpZMjRkSGZWMEhMeTN1
        aTRCSDhEdjNwTGhjVE02VXYzbUF5UEdSdVRzCmlEaUF3OWE0YmZGa1BvNjNXUmM2
        SEh6Q1A1WFFjSWFuaCs4WGdneDA2bmcKLS0tIEtDTi9scVZwaVppQ2ZHakxYWkZu
        dnVmR0hzTVZtRDhtZ1BjVW5Ca2RjM2MKHzK09cSrUzNJW+0FLz1xzgzciB1fFgJj
        CjXYT/NIqKFDfYdScFufZ4IQ5gDXCjJWb3576bX68PFyJ5cz0sLBOA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-01-18T14:43:05Z"
  mac: ENC[AES256_GCM,data:54Cm3jugyeUCIcSy5yv/MOvwBs8qX3N7Mcofe+rtzDFcqrKqkIrKGBrz/A87GcbUBsQNTFpkJwHINO+J+S1nK2lkHPVJzcO6EIFFS7ARU3OxLhi/MZpujJsXU9IOrw/xw/IdODBqGumCJoUgQJEqPWOiI1eImedRGF/XR00HkJ0=,iv:tM7ShRAEv4iwApLu3Lw+/wfiUC9SI5DTBLGB6lUHuoc=,tag:XimgzFbEJXUIwoUH0pVObQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
