apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-tunnel-secret
stringData:
  TUNNEL_TOKEN: ENC[AES256_GCM,data:UpPfZsYWP+M95ZY44kf+L78q/flmB2vgy7nVeioKrAGE72wKgtHOuK3ZHhRs7qS0xWOAmPiwlozpe1b472DNGuMhpa5mUh/cueQq2MqnjIppnt4SluqSRX2G4W+2LQlIh15xKB/nDgMuxiVXNIXoi8PyTZyJFlGC5f6dwzIF2DLBbZncTQiH46q+AmSBEfrbtTeut/3wWjhgnVh3+PepeoXgNXFKaPEJFY40smhtqHSJLKMh,iv:lNZKLuSTSQHE8PRrUErgA3uYtB3/q3liEgkG8VCFRYY=,tag:+ci2MzTeQiM+KloeDOb0bQ==,type:str]
sops:
  age:
    - recipient: age182kynq27uxu9tdjrk8neh0hztkra3xrxhjumwxsq9np9ms0ah5hsd0gjkz
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBnbmRZbEFZVVRiZkZsczVG
        Z1RmRzgxRmwxQjVHWDFYelhRaXNkSGM3dXlRClc3cS9xN3BCK1c3SlpYQkY4dEJu
        QStLS1FvVk54NHRoS1RWcXBaQTl4Z2MKLS0tIGxaM28wUGdFeWFkcklxUnJubnB4
        SGdNczl5WVN6OUY1b3EycEdqNWRwemsK1ZLI3N6zLC1jPl5+kE4w/h8Kp+f0hSZf
        AxB7ATqBMjRFJAi4ulx3u0UlOHOALch81Z5jHzND3eU5YWiOrnQ/ww==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-01-17T18:25:22Z"
  mac: ENC[AES256_GCM,data:THO9NJPzMFCOHelJFXaIEIMNyzcoIeOu2zWOcnOjB3u3ZBgd7iv7ocg3lN3KKuDu1iKK4gZrlog4B581YlzMw2n7Yv0JtT7f0PKQZzpD5jKDMLuJmIMHl4rUj25ma4IMcp0HZLJDd6b62zTEo91CrOkVh3jfJoPIK+O4LZACMG0=,iv:QiB/5Xt35s+YK5FojeVx0Sy5CavXehlFgG1NJWY4OZ8=,tag:8YZhWfKZ78V8/CLQ0FOO2A==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
