apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-tunnel-secret
stringData:
  TUNNEL_TOKEN: ENC[AES256_GCM,data:cq1aOXGTHKYiv4PsW5XrMtqVTPxPWbq5glsoG5ndzfI+TqNfW66UNkz+pGFySkEmRl4JAH/8PDBqQo+tWWm6+ymKmga0XuSmFgK8GkYDIGYLOKARxh0DRqQcmP/8t62sCIi/kn4LtiUJkKUzgaOmn3/XDVtuAnKEyVmfRPfRjdoBlKyv+Ckb2kJpxfvyhi79CZSSLyxEO9vz4NVvqbHByItrHorXHFnb2Vv3Pyn37BBLyoEG,iv:ZjltiQnN/TmJ162aDo9soXTqfv2UqSIqE3/5nj4ALpc=,tag:2oVHhVCZxp4DqtJSfeJTNw==,type:str]
sops:
  age:
    - recipient: age182kynq27uxu9tdjrk8neh0hztkra3xrxhjumwxsq9np9ms0ah5hsd0gjkz
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBMSXkwV1JFWTdIM3dnTm9M
        aEZKTlVUN1pSN0xabGM1UVpzMGhScUNWQ2pJClgzVmNkc09EanNxbVNwZVdtUXhE
        Sys2eVk4QmlRZkNrOGlGeEZvZjRSbmsKLS0tIDhiaTlrZWg3QTN2Q0NpQW5RT0x5
        SkNUVEFxNUhGMTZTQWhWekUvSUJSZUEKfB9bVUEbFdQEZAWFMDfrVwAFHx2DRW8B
        SphcsL7yuw/q56h7aqoq7RJ9q5vbkPd1UqCF7i/65vs6ytR660yWng==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-01-22T15:34:48Z"
  mac: ENC[AES256_GCM,data:V+6TqxR/A5ceZjEyuQQnW137fxZK36Rdnw3NSmd2J9kMGnsRBp7dMyLK057pXxziOZQE7yKOjs8J7i+OCSwfBn64Hysa1L8+7cSzHGLsQ0mgvNoBImdWM/tQUtlkvCUUMjUoCCXVfV2n5Fyq17qVJAEahA1Dte6K9Fvy/IF9tds=,iv:dUsErug0KnJo8BhCkUksMgvKc/WtjFeQJoMLiv1tKgk=,tag:eVQRduCpCSXgfhpRLUo6hw==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
