apiVersion: v1
kind: Secret
metadata:
  name: cert-manager-secret
stringData:
  api-token: ENC[AES256_GCM,data:O4WXib9axY2qnLoVqxAhawDSyFaNjKJgsNKxyC/OTQKaT8WkAfymwQ==,iv:sNjPqEVTKnhkuhFUsMSkhaE5LxMkfCmWZCcJJAkr1II=,tag:k7jgCv1xRe/DLrt41h0nvg==,type:str]
sops:
  age:
    - recipient: age182kynq27uxu9tdjrk8neh0hztkra3xrxhjumwxsq9np9ms0ah5hsd0gjkz
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTMmJWV29lb04rd2RtNWRR
        aVExajVnZWhpSjVKTjJUbWdreDBKbWZHY25rCmdiQzBtaHpiVE1HNDdkdzZiY2ov
        RmdvRkgvRUoxQ3pzZzVVNzIxLyswTUUKLS0tIERRNElXRFh1eEJFNTFGbE0rSHYx
        QUpXOHZ5cFNFVHdTSXYvOU1VMWRxZTAKH+f+fKqqTu4qkuORbr3wz1Wy3NjK0QyC
        GevBRm8xI+cUCH1BwWeJlBo+CCm2b6xhdcKxyIJtUEpNxstkGZoUSg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-01-18T14:43:05Z"
  mac: ENC[AES256_GCM,data:yRqMDHacJ1qFzNJzQ4y0fX5zpQvtDCX0C1vW7iT64/xuWe4jC9dnsEHLi8xu5HjS2bmRbyqhoPniplgaULTENTePD5EZcspIZF7tFyqv3/BLuBpXKsa34LGF4gz95nKRjiZSGM5ZgdKNIpZI0yT5XECB+uHHyPpDurTFUhWAfWM=,iv:umNqVWwff8KCuMh3WQ0mP6K2aL9Gs/Hvlfwc3HBqlOw=,tag:nrMC27iQcwtNr+lfnL11Ew==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
