apiVersion: v1
kind: Secret
metadata:
  name: cert-manager-secret
stringData:
  api-token: ENC[AES256_GCM,data:q8bmBU/Xml+3qCSpqF4Qcr5P1RISAljYktqAFJrjPBoQGZq1AObklQ==,iv:e1qDDJBVMdFKISAh2CFG1HXWAnTuAujXnIRfT/5kEs0=,tag:Y1oxE+DPJgPb7RJL8l8w+g==,type:str]
sops:
  age:
    - recipient: age182kynq27uxu9tdjrk8neh0hztkra3xrxhjumwxsq9np9ms0ah5hsd0gjkz
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6R25pUXQ2eHBxM012OW1C
        ckVvYWFiNU1JNk9LaEx0ZmRPdGR6SVhwaUdjCnNadFA5NDY0Znc5K1ZCQXlYN2VX
        KzRVcGc4ZFJxbGNrbHhKUVUyZjJZMjgKLS0tIGt2Q2MycnFENFlMYlROYzB4WFNk
        SUl1MzdHTDMzVFlGQ2hiMkVvS3FQa1kKwGBBDo7k8xEshqyhDrOnQYBy/H2k/YJD
        bTAPRrSERYEge39S8q2wPvXbkK4DW6wrIbNQoo8ceq1SWQ8Kmj4Ksw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-01-17T18:25:22Z"
  mac: ENC[AES256_GCM,data:VObAGGpo2S5NPRQ94d7SVS42XFakz/IpwSrAaJMJ4m1QC4xFJLXhZrNgnumeM2lOoTIPR0by7uUMACDjOpl2QbHNY5831BATXmOWW008DuhQnhhDrmy9/0PAutU2A8jF0jTt0oBXiNXZJ5BS7m+ccJau2bNtIzK82sovRidgWWk=,iv:stN7migXd0vGkHAOte0M4Ggh/wHhcruc6+29C6lZKbo=,tag:RYHfZYSvt0zOE3vB9qgyDw==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
