apiVersion: v1
kind: Secret
metadata:
  name: cert-manager-secret
stringData:
  api-token: ENC[AES256_GCM,data:33KUVNMRXuZMLpKpREqiTit9sKrX4Lk1asx6tYCdka9omUyRM//ToQ==,iv:OVKmWvrq9nnEPMBcaH5cre6egwDc3tFONc/sUw+PWyY=,tag:qnyH+LJc+1Dx7HokrH0PZQ==,type:str]
sops:
  age:
    - recipient: age182kynq27uxu9tdjrk8neh0hztkra3xrxhjumwxsq9np9ms0ah5hsd0gjkz
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBlazdoSUlSd1l3anJsZEtE
        RWwxQ1ErM1E4UmlGb0tJM2ZXVktsMngxNzJZClNOU2hpbnVvSjJkWTY5Rk0ycExE
        MXpaTDF3NkxIeURndWRpYS84K2NXZVUKLS0tIEk2QktkeDlOQ1Y5Q3htYmVDbFNs
        S1RiSjcwbnU3K0xaUTVwdlhzc0w2ME0KJPUHhdj1DjRRk+2ocfJK6TD4LNa1WyZb
        3AxRBgC3v8enJrj/ViKwXLC1HvvGeL43KvP3/k0xrQ7ZJKuZCsa/4A==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-01-22T15:34:48Z"
  mac: ENC[AES256_GCM,data:EkU3YQZr8h0cWTUMY1emXQ4nTou1n2h9OxU/DiS5RRIqionaJKuJ+KXrhrJvF1zpEbJHi9XkngYpT5oB2DM6ov7PMsaNZHTrYgeLBDc1Hr6VnzRp/IULQRAqMO/nt+y+8nsI307IoBubaZ3qLDAvI7BssUXzsxft1+vZUp+B8Yc=,iv:SAfcwktuJtc3JtEfEGv/Ksqjho2odPyHfhFQ5fjWvik=,tag:MLM3ooebdCtcAsAaSRRfJQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
