apiVersion: v1
kind: Secret
metadata:
  name: cert-manager-secret
stringData:
  api-token: ENC[AES256_GCM,data:Q51Ylap0mLHmkyrO5vb97Ck10OkA/CODC3C2YlgpH8YZdFlw56IjAQ==,iv:QAAUp78Wsn6tW2GS8g603xTaofKOJNVgIu9hlcpQF8M=,tag:ePUT8voPg3YqnVakQRjikw==,type:str]
sops:
  age:
    - recipient: age182kynq27uxu9tdjrk8neh0hztkra3xrxhjumwxsq9np9ms0ah5hsd0gjkz
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5L09oRFZobjI3bXVnZGdm
        amxIV3A5dTU0RG5BaVpIdWNVeFpSUGtyeUFBCkxTOW1yeDgyOEJTdEdZblJPVGtC
        N2F3eWlRYUl1NVd3VndZNzJ1OURuNEUKLS0tIEluUFRjak9SQlRoaTVFYTF4UnBF
        REtNNHl4NGFLWTl5ZzQ3WXQzUllCSzgKCuTB5SXqr5hHT9pFkz4Rgre21lXvfcBy
        gYlqOglqZ3CZWOTO7iVMPEw/85tTlAs5HKuv2F1T6+F4kbFeU1H+vA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-01-18T12:04:46Z"
  mac: ENC[AES256_GCM,data:4zFREvIoaBU/QxXfhAGsItEyP6RmMD3sQPYdMatlA/SDImcyFMdkf6RuIODhVwmB2IoAsjYJK6wNY/gmc2nqGaNXVIkUl+dRlU1cxXXsK6yFbMyTK/Qsz45+O0zxpNd9tBZ+ZKF791hMHI/0wGYtm/Ing0PxS+GKQx7pnTRv4xg=,iv:GRQJ8sHRQcsubbZ0yW8QttaAgO6Ic88ISGW0g0WPL8o=,tag:yR0IahgRn/kwIZ1juxo/8g==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
