apiVersion: v1
kind: Secret
metadata:
  name: cert-manager-secret
stringData:
  api-token: ENC[AES256_GCM,data:7VA1gTQCd/Po0Tas/GrW8HM9ph6M3H45Y8vwYXyYDcWnD3LL8JlwGw==,iv:+4JioGuzvajuOKfgQAvP6gJSPxFf8ddKqmM9eVkaZTY=,tag:Kz4D4gmYrPyhlTaEouGhgg==,type:str]
sops:
  age:
    - recipient: age182kynq27uxu9tdjrk8neh0hztkra3xrxhjumwxsq9np9ms0ah5hsd0gjkz
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYQ2RNWTFmMHozOGVQckxi
        b0xra253UjhCZFlGT2VGeCt3QkxFdUZTZW1zCjlsd043aDZtU0RhQWJ1dmJrdk01
        QWNuS0MrVFIreG5tVlUyMjJGRlRhY1UKLS0tIFNXbEsyNlk1a1pYY3ZJNm5pMEN3
        bWJVSDB3eDlOODkxNmRLUFIvK2RNUEUKMPftv3SGNTdwbPF7i/CvS0KMPNnScdPF
        ma81WV71Yzf7Bz4OmkiSjmYArXN7SxjbBXXjD0hloRANtHAU+NZzJQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-01-17T18:35:42Z"
  mac: ENC[AES256_GCM,data:pSB67HTnf4Aw0LTfdZsc+MtHv5+MxJMLvZSY3VK8WHE3gimSKjIaNWgfh8qHJhCY8v/USeeiZurYprpUCD6GXbgYV6LxoCXOB4pxTM7Qk7LLQkxkGHEqZK01PTFy/70DwhNKqmAVHa2ikPD0G5fDMWFRL4CeCm5rEmhSSFmHMuY=,iv:9cdfvzz2Atwd4/9LwEKFLc6dsh9/78JXIyJD8CeJxq4=,tag:2WcPE9ckMAVPQ8cOI6vEzw==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
