---
clusterName: kubernetes

talosVersion: "${talosVersion}"
kubernetesVersion: "${kubernetesVersion}"

endpoint: https://10.69.40.20:6443
additionalApiServerCertSans: &sans
  - "127.0.0.1"
  - "10.69.40.20"
additionalMachineCertSans: *sans

clusterPodNets: ["10.42.0.0/16"]
clusterSvcNets: ["10.43.0.0/16"]

# Disable built-in CNI to use Cilium
cniConfig:
  name: none

nodes:
  - hostname: "lilith-talos-master-1"
    ipAddress: "10.69.40.21"
    installDisk: "/dev/nvme0n1"
    machineSpec:
      secureboot: false
    talosImageURL: factory.talos.dev/installer/ddf38e55e30aa9b2bb0b765054ed63444dc00244ab8bb4ad4ad92486602285f8
    controlPlane: true
    networkInterfaces:
      - deviceSelector:
          hardwareAddr: "08:c0:eb:bd:c9:a8"
        dhcp: false
        addresses:
          - "10.69.40.21/24"
        routes:
          - gateway: "10.69.40.1"
            network: 0.0.0.0/0
        mtu: 1500
        vip:
          ip: "10.69.40.20"
    patches:
      - # Load kernel modules
        |-
        machine:
          kernel:
            modules:
              - name: nvme_tcp
              - name: vfio_pci
              - name: uio_pci_generic
  - hostname: "lilith-talos-master-2"
    ipAddress: "10.69.40.22"
    installDisk: "/dev/nvme0n1"
    machineSpec:
      secureboot: false
    talosImageURL: factory.talos.dev/installer/ddf38e55e30aa9b2bb0b765054ed63444dc00244ab8bb4ad4ad92486602285f8
    controlPlane: true
    networkInterfaces:
      - deviceSelector:
          hardwareAddr: "e4:1d:2d:2a:01:30"
        dhcp: false
        addresses:
          - "10.69.40.22/24"
        routes:
          - gateway: "10.69.40.1"
            network: 0.0.0.0/0
        mtu: 1500
        vip:
          ip: "10.69.40.20"
    patches:
      - # Load kernel modules
        |-
        machine:
          kernel:
            modules:
              - name: nvme_tcp
              - name: vfio_pci
              - name: uio_pci_generic
  - hostname: "lilith-talos-master-3"
    ipAddress: "10.69.40.23"
    installDisk: "/dev/nvme0n1"
    machineSpec:
      secureboot: false
    talosImageURL: factory.talos.dev/installer/ddf38e55e30aa9b2bb0b765054ed63444dc00244ab8bb4ad4ad92486602285f8
    controlPlane: true
    networkInterfaces:
      - deviceSelector:
          hardwareAddr: "08:c0:eb:bd:c3:8c"
        dhcp: false
        addresses:
          - "10.69.40.23/24"
        routes:
          - gateway: "10.69.40.1"
            network: 0.0.0.0/0
        mtu: 1500
        vip:
          ip: "10.69.40.20"
    patches:
      - # Load kernel modules
        |-
        machine:
          kernel:
            modules:
              - name: nvme_tcp
              - name: vfio_pci
              - name: uio_pci_generic

# Global patches
patches:
  - "@./patches/global/machine-files.yaml"
  - "@./patches/global/machine-kubelet.yaml"
  - "@./patches/global/machine-network.yaml"
  - "@./patches/global/machine-sysctls.yaml"
  - "@./patches/global/machine-time.yaml"

# Controller patches
controlPlane:
  patches:
    - "@./patches/controller/cluster.yaml"

